#!/usr/bin/env python3
"""Dependency-free Hindsight retain → recall → reflect integration smoke test.

Creates an isolated synthetic bank, writes two deterministic facts synchronously,
verifies recall and reflect contain the expected synthetic markers, then deletes the
entire bank unless --keep-bank is supplied. No personal data or Codex/OpenAI auth is
required.
"""
from __future__ import annotations

import argparse
import json
import os
import time
import urllib.error
import urllib.parse
import urllib.request
from typing import Any


def request(base_url: str, method: str, path: str, body: dict[str, Any] | None, timeout: int) -> Any:
    url = base_url.rstrip("/") + path
    data = json.dumps(body).encode("utf-8") if body is not None else None
    headers = {"Accept": "application/json"}
    if body is not None:
        headers["Content-Type"] = "application/json"
    api_key = os.environ.get("HINDSIGHT_API_KEY")
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as response:
            raw = response.read().decode("utf-8", errors="replace")
            if not raw.strip():
                return None
            try:
                return json.loads(raw)
            except json.JSONDecodeError:
                return raw
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"HTTP {exc.code} from {url}: {detail}") from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f"Could not reach {url}: {exc}") from exc


def flatten_strings(value: Any) -> list[str]:
    out: list[str] = []
    if isinstance(value, str):
        out.append(value)
    elif isinstance(value, dict):
        for item in value.values():
            out.extend(flatten_strings(item))
    elif isinstance(value, (list, tuple)):
        for item in value:
            out.extend(flatten_strings(item))
    return out


def contains(value: Any, needle: str) -> bool:
    wanted = needle.casefold()
    return any(wanted in text.casefold() for text in flatten_strings(value))


def retain(base_url: str, bank: str, content: str, document_id: str, timeout: int) -> Any:
    path = f"/v1/default/banks/{urllib.parse.quote(bank, safe='')}/memories"
    body = {
        "items": [
            {
                "content": content,
                "document_id": document_id,
                "context": "hermes-privacy-stack synthetic integration smoke test",
                "tags": ["hps-smoke-test"],
            }
        ],
        "async": False,
    }
    return request(base_url, "POST", path, body, timeout)


def recall(base_url: str, bank: str, query: str, timeout: int) -> Any:
    path = f"/v1/default/banks/{urllib.parse.quote(bank, safe='')}/memories/recall"
    return request(base_url, "POST", path, {"query": query, "budget": "low", "max_tokens": 1000}, timeout)


def reflect(base_url: str, bank: str, query: str, timeout: int) -> Any:
    path = f"/v1/default/banks/{urllib.parse.quote(bank, safe='')}/reflect"
    return request(base_url, "POST", path, {"query": query, "budget": "low", "max_tokens": 1000}, timeout)


def delete_bank(base_url: str, bank: str, timeout: int) -> bool:
    path = f"/v1/default/banks/{urllib.parse.quote(bank, safe='')}"
    try:
        request(base_url, "DELETE", path, None, timeout)
        return True
    except RuntimeError as exc:
        print(f"! Could not delete synthetic bank {bank}: {exc}")
        return False


def main() -> int:
    parser = argparse.ArgumentParser(description="Hindsight retain/recall/reflect smoke test")
    parser.add_argument(
        "--url",
        default=os.environ.get("HINDSIGHT_API_URL", "http://127.0.0.1:8888"),
        help="Hindsight API base URL",
    )
    parser.add_argument("--bank", help="Synthetic bank name; a unique value is generated by default")
    parser.add_argument("--timeout", type=int, default=180, help="Per-request timeout in seconds")
    parser.add_argument("--keep-bank", action="store_true", help="Do not delete the synthetic bank afterward")
    parser.add_argument("--json", action="store_true", help="Emit result summary as JSON")
    args = parser.parse_args()

    stamp = f"{int(time.time())}-{os.getpid()}"
    bank = args.bank or f"hps-smoke-{stamp}"
    token_a = f"PEBBLE-QUARTZ-{stamp}"
    token_b = f"MINT-ORBIT-{stamp}"

    summary: dict[str, Any] = {
        "bank": bank,
        "url": args.url.rstrip("/"),
        "retain": False,
        "recall": False,
        "reflect": False,
        "cleanup": False,
    }

    return_code = 1
    try:
        first = retain(
            args.url,
            bank,
            f"Synthetic Project Cobalt-Lantern has deployment marker {token_a}.",
            f"hps-smoke-a-{stamp}",
            args.timeout,
        )
        second = retain(
            args.url,
            bank,
            f"Synthetic Project Cobalt-Lantern has maintenance marker {token_b}.",
            f"hps-smoke-b-{stamp}",
            args.timeout,
        )
        summary["retain"] = bool(first is not None and second is not None)
        if not summary["retain"]:
            raise RuntimeError("retain returned an empty response")

        recalled = recall(
            args.url,
            bank,
            "What are the deployment and maintenance markers for Synthetic Project Cobalt-Lantern?",
            args.timeout,
        )
        summary["recall"] = contains(recalled, token_a) and contains(recalled, token_b)
        if not summary["recall"]:
            raise RuntimeError("recall did not return both synthetic markers")

        reflected = reflect(
            args.url,
            bank,
            "State both markers for Synthetic Project Cobalt-Lantern. Do not invent any other marker.",
            args.timeout,
        )
        summary["reflect"] = contains(reflected, token_a) and contains(reflected, token_b)
        if not summary["reflect"]:
            raise RuntimeError("reflect did not return both synthetic markers")

        summary["ok"] = True
        return_code = 0
    except Exception as exc:
        summary["ok"] = False
        summary["error"] = str(exc)
    finally:
        if args.keep_bank:
            summary["cleanup"] = False
            summary["kept"] = True
        else:
            summary["cleanup"] = delete_bank(args.url, bank, args.timeout)
            if not summary["cleanup"] and return_code == 0:
                summary["ok"] = False
                summary["error"] = "memory checks passed but synthetic bank cleanup failed"
                return_code = 1

    if args.json:
        print(json.dumps(summary, indent=2))
    else:
        for key in ("retain", "recall", "reflect"):
            print(("✓" if summary.get(key) else "✗"), key)
        print(("✓" if summary.get("cleanup") else "ℹ"), "synthetic bank cleanup")
        if summary.get("ok"):
            print(f"Hindsight smoke test passed: {bank}")
        else:
            print(f"Hindsight smoke test failed: {summary.get('error', 'unknown error')}")

    return return_code


if __name__ == "__main__":
    raise SystemExit(main())
