#!/usr/bin/env python3
"""Resolve strict-free v2 Compose images to immutable OCI digests.

The explicit source list is also a policy gate: Compose cannot gain an unreviewed image
without this tool failing. Runtime secrets/personal state are never read.
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
COMPOSE = ROOT / "stack" / "compose.yml"

SOURCES: dict[str, str] = {
    "HPS_MEMORY_IMAGE": "ghcr.io/doobidoo/mcp-memory-service:latest",
    "HPS_SEARXNG_IMAGE": "searxng/searxng:latest",
    "HPS_DOCLING_IMAGE": "quay.io/docling-project/docling-serve:latest",
    "HPS_LLAMA_IMAGE": "ghcr.io/ggml-org/llama.cpp:server",
    "HPS_CRAWL4AI_IMAGE": "unclecode/crawl4ai:0.8.6",
    "HPS_NODERED_IMAGE": "nodered/node-red:4.1.10",
    "HPS_FORGEJO_IMAGE": "codeberg.org/forgejo/forgejo:15.0.8",
}

DIGEST_RE = re.compile(r"^.+@sha256:[0-9a-f]{64}$")


def run(cmd: list[str], *, capture: bool = False, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    print("+", " ".join(cmd))
    return subprocess.run(cmd, check=True, text=True, capture_output=capture, env=env)


def source_ref(name: str, default: str) -> str:
    return os.environ.get(name, default).strip()


def repo_name(ref: str) -> str:
    if "@" in ref:
        return ref.split("@", 1)[0]
    slash = ref.rfind("/")
    colon = ref.rfind(":")
    return ref[:colon] if colon > slash else ref


def compose_images() -> set[str]:
    if not shutil.which("docker"):
        raise SystemExit("docker is required for release image resolution")
    env = os.environ.copy()
    env.setdefault("HPS_MEMORY_API_KEY", "image-lock-not-a-runtime-secret")
    env.setdefault("HPS_NODERED_CREDENTIAL_SECRET", "image-lock-not-a-runtime-secret")
    env.setdefault("HPS_LLAMA_MODEL_DIR", str(ROOT))
    env.setdefault("HPS_LLAMA_MODEL_FILE", "image-lock-placeholder.gguf")
    cmd = ["docker", "compose", "-f", str(COMPOSE)]
    for profile in ("core", "local-model", "research", "automation", "git"):
        cmd += ["--profile", profile]
    proc = run(cmd + ["config", "--images"], capture=True, env=env)
    return {line.strip() for line in proc.stdout.splitlines() if line.strip()}


def configured_sources() -> dict[str, str]:
    return {name: source_ref(name, default) for name, default in SOURCES.items()}


def validate_compose_coverage() -> dict[str, str]:
    configured = configured_sources()
    expected = set(configured.values())
    actual = compose_images()
    if actual != expected:
        missing = sorted(actual - expected)
        stale = sorted(expected - actual)
        details = []
        if missing:
            details.append("unreviewed Compose images: " + ", ".join(missing))
        if stale:
            details.append("lock sources not present in Compose: " + ", ".join(stale))
        raise SystemExit("image-lock coverage mismatch; " + "; ".join(details))
    return configured


def resolve_digest(source: str, pull: bool) -> dict[str, Any]:
    if pull:
        run(["docker", "pull", source])
    proc = run(["docker", "image", "inspect", source], capture=True)
    payload = json.loads(proc.stdout)
    if not isinstance(payload, list) or not payload:
        raise SystemExit(f"docker inspect returned no data for {source}")
    info = payload[0]
    digests = info.get("RepoDigests") or []
    repo = repo_name(source)
    pinned = next((d for d in digests if d.startswith(repo + "@sha256:")), None) or (digests[0] if digests else None)
    if not pinned or not DIGEST_RE.match(pinned):
        raise SystemExit(f"could not obtain immutable digest for {source}: {digests}")
    return {
        "source": source,
        "digest_ref": pinned,
        "image_id": info.get("Id"),
        "os": info.get("Os"),
        "architecture": info.get("Architecture"),
    }


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_outputs(output_dir: Path, entries: dict[str, dict[str, Any]]) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    env_path = output_dir / "images.lock.env"
    json_path = output_dir / "images.lock.json"
    sums_path = output_dir / "SHA256SUMS"
    env_path.write_text(
        "# Generated by scripts/image_lock.py after strict-free review.\n" +
        "\n".join(f"{name}={entries[name]['digest_ref']}" for name in sorted(entries)) + "\n",
        encoding="utf-8",
    )
    json_path.write_text(json.dumps({
        "schema": 2,
        "architecture": "strict-free-v2",
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "repository": os.environ.get("GITHUB_REPOSITORY", "JDsnyke/hermes-privacy-stack"),
        "git_sha": os.environ.get("GITHUB_SHA"),
        "images": entries,
    }, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    sums_path.write_text(
        f"{sha256_file(env_path)}  {env_path.name}\n{sha256_file(json_path)}  {json_path.name}\n",
        encoding="utf-8",
    )


def self_test() -> None:
    tests = {
        "ubuntu:latest": "ubuntu",
        "ghcr.io/acme/tool:v1": "ghcr.io/acme/tool",
        "registry.example:5000/acme/tool:edge": "registry.example:5000/acme/tool",
        "example/tool@sha256:" + "a" * 64: "example/tool",
    }
    for ref, expected in tests.items():
        if repo_name(ref) != expected:
            raise SystemExit(f"repo parsing failed for {ref}")
    if any(term in " ".join(SOURCES.values()).lower() for term in ("nango", "activepieces", "hindsight", "ollama", "netbird")):
        raise SystemExit("strict-free source policy regression")
    print("image-lock strict-free self-test passed")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", default="dist/supply-chain")
    parser.add_argument("--no-pull", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        self_test()
        return 0
    configured = validate_compose_coverage()
    entries = {name: resolve_digest(source, pull=not args.no_pull) for name, source in configured.items()}
    write_outputs(Path(args.output_dir), entries)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
