#!/usr/bin/env python3
"""Resolve Hermes Privacy Stack container sources to immutable OCI digests.

This tool is intended for release/manual supply-chain validation. It never changes the
running stack. It pulls the configured source tags, verifies the Compose image set has
not drifted from this audited list, and emits:

- images.lock.env   HPS_*_IMAGE variables using repo@sha256 references
- images.lock.json  provenance-friendly metadata for every resolved image
- SHA256SUMS        hashes of both lock files

Runtime secrets and personal state are never read.
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
COMPOSE = ROOT / "stack" / "compose.yml"

# Keep this list explicit. If Compose gains an image, normal resolution must fail
# until the new image and its trust implications are reviewed here.
SOURCES: dict[str, str] = {
    "HPS_OLLAMA_IMAGE": "ollama/ollama:latest",
    "HPS_CURL_IMAGE": "curlimages/curl:latest",
    "HPS_HINDSIGHT_IMAGE": "ghcr.io/vectorize-io/hindsight:latest",
    "HPS_SEARXNG_IMAGE": "searxng/searxng:latest",
    "HPS_DOCLING_IMAGE": "quay.io/docling-project/docling-serve:latest",
    "HPS_ACTIVEPIECES_IMAGE": "activepieces/activepieces:latest",
    "HPS_NANGO_POSTGRES_IMAGE": "postgres:16.0-alpine",
    "HPS_NANGO_IMAGE": "nangohq/nango-server:hosted",
}

DIGEST_RE = re.compile(r"^.+@sha256:[0-9a-f]{64}$")


def run(cmd: list[str], *, capture: bool = False) -> subprocess.CompletedProcess[str]:
    print("+", " ".join(cmd))
    return subprocess.run(cmd, check=True, text=True, capture_output=capture)


def source_ref(env_name: str, default: str) -> str:
    return os.environ.get(env_name, default).strip()


def repo_name(ref: str) -> str:
    """Strip a tag/digest without confusing registry host ports with tags."""
    if "@" in ref:
        return ref.split("@", 1)[0]
    slash = ref.rfind("/")
    colon = ref.rfind(":")
    return ref[:colon] if colon > slash else ref


def compose_images() -> set[str]:
    if not shutil.which("docker"):
        raise SystemExit("docker is required")
    proc = run(
        [
            "docker",
            "compose",
            "-f",
            str(COMPOSE),
            "--profile",
            "core",
            "--profile",
            "automation",
            "--profile",
            "nango",
            "config",
            "--images",
        ],
        capture=True,
    )
    return {line.strip() for line in proc.stdout.splitlines() if line.strip()}


def configured_sources() -> dict[str, str]:
    return {name: source_ref(name, default) for name, default in SOURCES.items()}


def validate_compose_coverage() -> dict[str, str]:
    configured = configured_sources()
    expected = set(configured.values())
    actual = compose_images()
    if actual != expected:
        missing = sorted(actual - expected)
        stale = sorted(expected - actual)
        details: list[str] = []
        if missing:
            details.append("unreviewed Compose images: " + ", ".join(missing))
        if stale:
            details.append("lock sources not present in Compose: " + ", ".join(stale))
        raise SystemExit("image-lock coverage mismatch; " + "; ".join(details))
    return configured


def resolve_digest(source: str, pull: bool) -> dict[str, Any]:
    if pull:
        run(["docker", "pull", source])
    proc = run(["docker", "image", "inspect", source], capture=True)
    payload = json.loads(proc.stdout)
    if not isinstance(payload, list) or not payload:
        raise SystemExit(f"docker inspect returned no data for {source}")
    info = payload[0]
    digests = info.get("RepoDigests") or []
    repo = repo_name(source)
    pinned = next((d for d in digests if d.startswith(repo + "@sha256:")), None)
    if pinned is None and digests:
        pinned = digests[0]
    if not pinned or not DIGEST_RE.match(pinned):
        raise SystemExit(f"could not obtain immutable sha256 RepoDigest for {source}: {digests}")
    return {
        "source": source,
        "digest_ref": pinned,
        "image_id": info.get("Id"),
        "os": info.get("Os"),
        "architecture": info.get("Architecture"),
    }


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_outputs(output_dir: Path, entries: dict[str, dict[str, Any]]) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    env_path = output_dir / "images.lock.env"
    json_path = output_dir / "images.lock.json"
    sums_path = output_dir / "SHA256SUMS"

    env_text = "# Generated by scripts/image_lock.py; use only after reviewing scan results.\n"
    env_text += "\n".join(f"{name}={entries[name]['digest_ref']}" for name in sorted(entries)) + "\n"
    env_path.write_text(env_text, encoding="utf-8")

    manifest = {
        "schema": 1,
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "repository": os.environ.get("GITHUB_REPOSITORY", "JDsnyke/hermes-privacy-stack"),
        "git_sha": os.environ.get("GITHUB_SHA"),
        "images": entries,
    }
    json_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    sums = [
        f"{sha256_file(env_path)}  {env_path.name}",
        f"{sha256_file(json_path)}  {json_path.name}",
    ]
    sums_path.write_text("\n".join(sums) + "\n", encoding="utf-8")

    print(f"✓ wrote {env_path}")
    print(f"✓ wrote {json_path}")
    print(f"✓ wrote {sums_path}")


def self_test() -> None:
    tests = {
        "ubuntu:latest": "ubuntu",
        "ghcr.io/acme/tool:v1.2.3": "ghcr.io/acme/tool",
        "registry.example:5000/acme/tool:edge": "registry.example:5000/acme/tool",
        "example/tool@sha256:" + "a" * 64: "example/tool",
    }
    for ref, expected in tests.items():
        actual = repo_name(ref)
        if actual != expected:
            raise SystemExit(f"repo_name({ref!r})={actual!r}, expected {expected!r}")
    if not DIGEST_RE.match("example/tool@sha256:" + "a" * 64):
        raise SystemExit("digest regex self-test failed")
    print("image-lock pure self-test passed")


def main() -> int:
    parser = argparse.ArgumentParser(description="Resolve Compose images to immutable OCI digests")
    parser.add_argument("--output-dir", default="dist/supply-chain")
    parser.add_argument("--no-pull", action="store_true", help="Resolve from already-present local images only")
    parser.add_argument("--self-test", action="store_true", help="Run pure parser checks without Docker")
    args = parser.parse_args()

    if args.self_test:
        self_test()
        return 0

    configured = validate_compose_coverage()
    entries: dict[str, dict[str, Any]] = {}
    for env_name, source in configured.items():
        print(f"\nResolving {env_name}: {source}")
        entries[env_name] = resolve_digest(source, pull=not args.no_pull)

    write_outputs(Path(args.output_dir), entries)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
